variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

bitstream:
  stage: build
  image: vivado2018:2018.3
  script:
    - env
    - /opt/Xilinx/Vivado/2018.3/bin/vivado -mode tcl -source build.tcl hw_alu.xpr

  artifacts:
    paths:
      - hw_alu.runs/impl_1/main.bit
      - hw_alu.runs/impl_1/runme.log
      - hw_alu.runs/synth_1/runme.log

